### ISSUE TITLE
Proposal: Display transfers using descriptive names

### ISSUE THREAD

**Issue by kroggen** [aergoio/aergoscan#30]
Currently the mint and burn operations are displayed on the Transfers tab using the `address0` (or 111111...) as the source or destination:

<img width="1161" alt="Screen Shot 2022-01-27 at 02 22 36" src="https://user-images.githubusercontent.com/7624275/151296930-39252494-27c5-4754-b719-9967f91443b2.png">

It is a bit confusing to understand what is going on, mainly for newbies.

What about instead of the "11111" use descriptive names like "MINT" and "BURN"?

But as some accounts may have names and the names can be displayed instead of the address, maybe instead of just "mint" and "burn" it could use some differing marks, like "&lt;&lt;MINT>>" or whatever, using characters that are not allowed in the account names.

Or even using different color either for the row background or for the text foreground.

This can be implemented after [this](https://github.com/aergoio/ARC1-Extensions/issues/10) is done

The same could also be applied to events from the WAERGO contract. It has events named "wrap" and "unwrap"

**Comment by graup** [comment]
Nice, this could be done fairly easily. I'll look into this.
