### ISSUE TITLE
API to retrieve list of tokens by symbol or name

### ISSUE THREAD

**Issue by kroggen** [aergoio/aergoscan#31]
It would be used to search for a given token by name or symbol

### Input:

String

### Output:

List of tokens in which the name OR symbol match the input

The match can be partial, like "starts with", so if the user types "A" the API would return all tokens in which the name or symbol starts with "A".

For each item in the list, returns:

* address
* name
* symbol

**Comment by graup** [comment]
See

https://api.aergoscan.io/main/token?q=(symbol:CNFT)%20OR%20(name:cccv_nft)

**Comment by kroggen** [comment]
Oh good!

It is exactly what I needed.

I was able to do a "start with" query by using a `*` at the end.

Thank you!
